import { useEffect, useState } from "react";
import { CheckCircleIcon, FileTextIcon, GaugeIcon, GitBranchIcon, PauseIcon, PlayIcon, ShieldCheckIcon, TimerIcon } from "@phosphor-icons/react";
import { LeadModal } from "./LeadModal.jsx";
import { setPageMetadata } from "./seo.js";

const steps = [
  ["01", "Build your forms", "Create payment, purchase, leave, contract, or clearance requests without code."],
  ["02", "Design the chain", "Map sequential, parallel, quorum, conditional, and automatic approval routes."],
  ["03", "Submit and decide", "Staff submit once. Approvers act securely from email, chat, or the app."],
  ["04", "See the truth", "Track every decision, deadline, bottleneck, and immutable audit event."],
];

const impactOutcomes = [
  { title: "Decisions move without the chase", copy: "Requests reach the right approver instantly, with every document and comment attached to one source of truth.", Icon: GaugeIcon, tone: "neutral" },
  { title: "Policies enforce themselves", copy: "Sequential, parallel, quorum, and amount-based rules route every request through the exact chain of authority.", Icon: GitBranchIcon, tone: "lilac" },
  { title: "Deadlines create clear ownership", copy: "SLA timers, reminders, delegation, and escalation keep urgent work from disappearing in someone’s inbox.", Icon: TimerIcon, tone: "mint" },
  { title: "Every decision is audit-ready", copy: "An immutable, append-only timeline proves who acted, what changed, and when—without reconstructing the story later.", Icon: ShieldCheckIcon, tone: "neutral" },
];

const workflowTabs = [
  { label: "Sequential", title: "Every decision, in the right order.", copy: "Route a request from line manager to finance to the CFO. Each person sees the context they need; nobody can skip the chain.", request: "Regional clinic equipment", amount: "$24,850", nodes: [{ title: "Line manager", meta: "Submitted with documents", event: "Request received and validated" }, { title: "Finance review", meta: "Budget and policy check", event: "Finance controller notified" }, { title: "CFO sign-off", meta: "Final authority", event: "Decision sealed in the audit trail" }] },
  { label: "Conditional", title: "Your policies become the route.", copy: "Send routine purchases straight through while higher-value requests automatically climb the authority ladder.", request: "New branch generator", amount: "$68,400", nodes: [{ title: "Amount check", meta: "Rule: over $50,000", event: "Value threshold matched" }, { title: "Budget owner", meta: "Funds confirmed", event: "Budget owner reviewing evidence" }, { title: "Executive sign-off", meta: "Added automatically", event: "Executive route created and logged" }] },
  { label: "Committee", title: "Quorum without the meeting chase.", copy: "Collect decisions in parallel and close the request as soon as the quorum you define has been reached.", request: "Vendor framework renewal", amount: "3 of 5", nodes: [{ title: "Invite reviewers", meta: "Five secure links sent", event: "Committee review opened" }, { title: "Quorum reached", meta: "Three approvals recorded", event: "Required quorum reached" }, { title: "Decision recorded", meta: "No meeting required", event: "Approved result made immutable" }] },
];

const featureGroups = [
  ["accountability", "Accountability", "Proof that outlives the conversation.", [["Immutable audit trail", "Every approval, rejection, comment, and return is permanently recorded."], ["SLA escalation", "Overdue requests move automatically instead of sitting unread."], ["Append-only records", "Actions can be added, never quietly rewritten or deleted."]]],
  ["speed", "Speed", "A faster yes. A clearer no.", [["Approve from anywhere", "Secure, expiring links work from email, Slack, Teams, Telegram, and WhatsApp."], ["Delegation", "Schedule a trusted fallback before leave or travel."], ["Smart reminders", "Respect quiet hours while keeping pending work visible."]]],
  ["flexibility", "Flexibility", "Built around how authority actually works.", [["No-code forms", "Shape every request around the fields, files, and policies your team needs."], ["Every approval pattern", "Sequential, parallel, quorum, conditional, auto-approve, and delegation."], ["Useful collaboration", "Followers, mentions, comments, and edit history live with the request."]]],
  ["insight", "Insight", "Find friction before it becomes delay.", [["Approval analytics", "Understand cycle time, bottlenecks, activity, and overdue work."], ["Exports for every audience", "Create CSV, Excel, and PDF reports for operations, boards, and auditors."], ["Search in seconds", "Find any request by reference, title, requester, or status."]]],
];

const industries = [
  ["Finance", "Loan, credit, expense, and committee approvals with exposure-based routing."], ["Public sector", "Procurement and memo routing with visible ownership and due-process evidence."], ["Healthcare", "Urgent supply and operational requests protected by deadlines and escalation."], ["Education", "Student, faculty, and finance approvals in one transparent chain."], ["Multi-site teams", "Branch requests decided centrally, without losing local context."],
];

const faqs = [
  ["What is ApprovalDesk?", "ApprovalDesk is an approval-workflow system for business requests, documents, notes, and memos. It routes each request through your chosen chain of authority and preserves a complete record of the decisions, comments, files, and deadlines around it."],
  ["Do we need an IT department to run it?", "No. ApprovalDesk is delivered as a managed instance. OHR Systems develops the product, while IChannel Technologies provides implementation and support. Our teams handle the infrastructure, deployment, and ongoing maintenance so your organisation can stay focused on its work."],
  ["Can it match our exact approval hierarchy?", "Yes. Workflows can be sequential, parallel, committee or quorum-based, conditional by amount or other rules, automatically approved, escalated, or delegated. Published workflow versions remain attached to the requests that used them, so later changes do not rewrite history."],
  ["How do approvers receive and decide on requests?", "Approvers work from a focused decision queue and can also receive time-limited links through email or enabled messaging channels. They can approve, approve with conditions, reject, return, request information, delegate, or escalate when the workflow permits."],
  ["What makes the audit trail reliable?", "ApprovalDesk adds every decision, revision, reminder, delegation, and workflow event as a new history entry. Recorded actions cannot be silently edited or removed. Authorised administrators and auditors can also create verifiable evidence packs for individual requests."],
  ["How are sensitive information and attachments protected?", "Your organisation controls roles and field-level access. Sensitive answers can be hidden from unauthorised users and redacted from exports, while private attachments are delivered through short-lived signed links. Access to sensitive values can also be logged for review."],
  ["Does ApprovalDesk connect with our existing tools?", "ApprovalDesk can support notifications and post-approval actions through configured services such as Microsoft Teams, Slack, Google Drive, SharePoint, OneDrive, Gmail, Outlook, webhooks, and other approved messaging channels. We confirm the integrations included in your managed setup during onboarding."],
  ["Where is our data hosted?", "Your data is hosted in a managed ApprovalDesk instance operated and maintained by our team. We discuss your security, access, backup, and data-location requirements during onboarding and document the agreed service arrangements."],
  ["Is a SaaS version available?", "Not yet. The current product is a managed instance supported by our team. A separate SaaS version is coming soon; talk to us if you would like to join the waitlist."],
];

function Brand({ tone = "dark" }) { return <a className="brand" href="#top" aria-label="ApprovalDesk home"><img src={`/images/brand/approvaldesk-logo-${tone}.png`} alt="ApprovalDesk" /></a>; }
function ActionLink({ children, secondary = false, onClick }) { return <a className={`button ${secondary ? "button-secondary" : "button-primary"}`} href="#demo" onClick={event => { if (onClick) { event.preventDefault(); onClick(); } }}><span>{children}</span><span>↗</span></a>; }
function Eyebrow({ children }) { return <p className="eyebrow"><span />{children}</p>; }

function AppMockup() {
  const [approved, setApproved] = useState(false);
  return <div className="approval-card">
    <div className="approval-top"><span>REQ-2026-0817</span><span className={approved ? "status approved" : "status"}>{approved ? "Approved" : "Awaiting decision"}</span></div>
    <div className="approval-body"><p className="micro">PURCHASE REQUEST</p><h3>Regional clinic equipment</h3><div className="amount-row"><span>Requested amount</span><strong>$24,850</strong></div>
      <div className="timeline"><div className="timeline-row done"><i>1</i><div><b>Department head</b><small>Approved · 09:42</small></div><em>Done</em></div><div className={`timeline-row ${approved ? "done" : "current"}`}><i>2</i><div><b>Finance controller</b><small>{approved ? "Approved just now" : "Your decision is due today"}</small></div><em>{approved ? "Done" : "Now"}</em></div><div className="timeline-row"><i>3</i><div><b>Executive director</b><small>Unlocks after finance</small></div><em>Next</em></div></div>
      <button className="approve-button" onClick={() => setApproved(v => !v)}>{approved ? "Undo preview" : "Approve request"}</button>
    </div></div>;
}

export function App() {
  const [menuOpen, setMenuOpen] = useState(false), [workflow, setWorkflow] = useState(0), [workflowStep, setWorkflowStep] = useState(0), [workflowPaused, setWorkflowPaused] = useState(false), [openFaq, setOpenFaq] = useState(0), [leadMode, setLeadMode] = useState(null), [impactActive, setImpactActive] = useState(0), [impactPaused, setImpactPaused] = useState(false), [featureTab, setFeatureTab] = useState(0), [featurePaused, setFeaturePaused] = useState(false);
  const openLead = mode => { setMenuOpen(false); setLeadMode(mode); };
  useEffect(() => { setPageMetadata({ title: "ApprovalDesk — Audit-ready approval workflows", description: "ApprovalDesk is managed, audit-ready approval workflow software for businesses. Route requests, automate decisions, and keep an accountable record of every action.", path: "/" }); }, []);
  useEffect(() => { const close = () => setMenuOpen(false); window.addEventListener("resize", close); return () => window.removeEventListener("resize", close); }, []);
  useEffect(() => {
    const selectFeatureFromHash = () => {
      const index = featureGroups.findIndex(group => group[0] === window.location.hash.slice(1));
      if (index >= 0) setFeatureTab(index);
    };
    selectFeatureFromHash();
    window.addEventListener("hashchange", selectFeatureFromHash);
    return () => window.removeEventListener("hashchange", selectFeatureFromHash);
  }, []);
  useEffect(() => { if (impactPaused) return undefined; const timer = window.setInterval(() => setImpactActive(current => (current + 1) % impactOutcomes.length), 3000); return () => window.clearInterval(timer); }, [impactPaused]);
  useEffect(() => {
    if (featurePaused || window.matchMedia("(prefers-reduced-motion: reduce)").matches) return undefined;
    const timer = window.setInterval(() => setFeatureTab(current => (current + 1) % featureGroups.length), 5000);
    return () => window.clearInterval(timer);
  }, [featurePaused]);
  useEffect(() => { setWorkflowStep(0); }, [workflow]);
  useEffect(() => {
    if (workflowPaused || window.matchMedia("(prefers-reduced-motion: reduce)").matches) return undefined;
    const timer = window.setInterval(() => setWorkflowStep(current => (current + 1) % workflowTabs[workflow].nodes.length), 2200);
    return () => window.clearInterval(timer);
  }, [workflow, workflowPaused]);
  return <div id="top">
    <div className="announce">Move work forward. Keep every decision accountable.<a href="#how">See how it works ↗</a></div>
    <header className="site-header"><div className="nav-shell"><Brand /><nav className={`nav-links ${menuOpen ? "open" : ""}`}>{[["How it works","how"],["Features","features"],["Industries","industries"],["Security","security"],["FAQ","faq"]].map(x=><a key={x[1]} href={`#${x[1]}`} onClick={()=>setMenuOpen(false)}>{x[0]}</a>)}</nav><a className="nav-cta" href="#demo" onClick={event=>{event.preventDefault();openLead("demo")}}>Book a demo ↗</a><button className="menu-button" onClick={()=>setMenuOpen(v=>!v)}>{menuOpen ? "Close" : "Menu"}</button></div></header>
    <main>
      <section className="hero section-shell"><div className="hero-copy"><Eyebrow>Audit-ready approval software</Eyebrow><h1>Stop chasing approvals in <em>group chats.</em></h1><p className="hero-lede">Route every request through your exact chain of authority—and keep a tamper-proof record of who approved what, and when.</p><div className="hero-actions"><ActionLink onClick={()=>openLead("demo")}>Book a managed demo</ActionLink><ActionLink secondary onClick={()=>openLead("waitlist")}>Join the SaaS waitlist</ActionLink></div><div className="hero-proof"><div className="avatars"><span>AO</span><span>MN</span><span>TK</span></div><div><b>Your managed instance, handled end to end</b><small>We configure, deploy, maintain, and support ApprovalDesk—so your team can focus on decisions, not infrastructure.</small></div></div></div><div className="hero-visual"><img src="/images/sections/hero-team.png" alt="Operations leaders reviewing an approval request" /><div className="hero-card-wrap"><AppMockup /></div><p className="image-label">DECISIONS / WITHOUT THE CHASE</p></div></section>
      <section className="trust-strip"><div className="logo-ticker"><span>FINANCE</span><i/><span>PROCUREMENT</span><i/><span>OPERATIONS</span><i/><span>HEALTHCARE</span><i/><span>EDUCATION</span><i/><span>PUBLIC SECTOR</span></div></section>
      <section className="intro section-shell"><Eyebrow>About ApprovalDesk</Eyebrow><h2>ApprovalDesk replaces the paper trail, follow-up calls, and guesswork with one clear system.</h2><div className="intro-notes"><div><b>Move faster</b><p>One request. The right route. A decision from anywhere.</p></div><div><b>Stay accountable</b><p>Every action is timestamped, attributed, and append-only.</p></div><div><b>Stay focused</b><p>Our team manages the infrastructure and maintenance behind your instance.</p></div></div></section>
      <section className="impact" id="how"><div className="section-shell impact-shell"><div className="impact-heading"><Eyebrow>Our impact</Eyebrow><h2>Faster decisions and<br/> total accountability</h2><a className="impact-cta" href="#demo" onClick={event=>{event.preventDefault();openLead("demo")}}>See ApprovalDesk in action <span>↗</span></a></div><div className="impact-grid"><div className="impact-image"><img src="/images/sections/workflow-team.png" alt="Operations team reviewing an approval workflow"/><span className="photo-chip">LIVE WORKFLOW</span><button className="impact-playback" type="button" aria-label={impactPaused ? "Resume outcome highlights" : "Pause outcome highlights"} onClick={() => setImpactPaused(value => !value)}>{impactPaused ? <PlayIcon size={22} weight="fill"/> : <PauseIcon size={22} weight="fill"/>}</button></div><div className="impact-cards">{impactOutcomes.map((outcome, index) => { const Icon = outcome.Icon; return <article className={`impact-card ${impactActive === index ? "active" : ""}`} key={outcome.title} onMouseEnter={() => setImpactActive(index)}><span className={`impact-icon ${outcome.tone}`}><Icon size={25} weight="regular"/></span><div><h3>{outcome.title}</h3><p>{outcome.copy}</p></div><span className="impact-index">0{index + 1}</span></article>; })}</div></div></div></section>
      <section className="systems section-shell"><div className="section-heading split"><div><Eyebrow>Workflow intelligence</Eyebrow><h2>Approval systems that match the real world.</h2></div><p>Turn policy into a route your team can follow without interpretation or manual chasing.</p></div><div className="workflow-tabs">{workflowTabs.map((x,i)=><button key={x.label} aria-selected={workflow===i} onClick={()=>setWorkflow(i)}>{x.label}</button>)}</div><div className="workflow-stage"><div className="workflow-copy"><p className="micro">{workflowTabs[workflow].label.toUpperCase()} ROUTING</p><h3>{workflowTabs[workflow].title}</h3><p>{workflowTabs[workflow].copy}</p><a href="#demo" onClick={event=>{event.preventDefault();openLead("demo")}}>Map your workflow ↗</a></div><div className="workflow-map"><div className="workflow-demo-bar"><div><span className="live-dot"/><span>Live approval</span><b>REQ-2026-0817</b></div><button type="button" onClick={()=>setWorkflowPaused(value=>!value)} aria-label={workflowPaused ? "Play approval workflow" : "Pause approval workflow"}>{workflowPaused ? <PlayIcon size={15} weight="fill"/> : <PauseIcon size={15} weight="fill"/>}<span>{workflowPaused ? "Play" : "Pause"}</span></button></div><div className="workflow-request"><FileTextIcon size={23}/><div><span>{workflowTabs[workflow].request}</span><b>{workflowTabs[workflow].amount}</b></div></div><div className="workflow-route">{workflowTabs[workflow].nodes.map((node,i)=>{const state=i<workflowStep?"done":i===workflowStep?"current":"pending";return <button type="button" className={`map-node ${state}`} key={node.title} onClick={()=>setWorkflowStep(i)} aria-label={`${node.title}: ${state}`}><span className="node-number">{state==="done"?<CheckCircleIcon size={17} weight="fill"/>:String(i+1).padStart(2,"0")}</span><b>{node.title}</b><small>{node.meta}</small><em>{state==="done"?"Complete":state==="current"?"In progress":"Up next"}</em></button>})}</div><div className="workflow-event" aria-live="polite"><span className="event-icon"><TimerIcon size={16}/></span><div><small>ACTIVITY NOW</small><b>{workflowTabs[workflow].nodes[workflowStep].event}</b></div><span className="event-time">just now</span></div></div></div></section>
      <section className="metrics"><div className="section-shell"><div className="metric-intro"><Eyebrow>Operational clarity</Eyebrow><h2>One system for every decision that matters.</h2><p>Give teams a faster way to move work—and give leadership an evidence trail they can trust.</p></div><div className="metric-cards"><div className="metric-card lilac"><strong>01</strong><h3>One-click</h3><p>Decisions from email, chat, or the app through secure links.</p></div><div className="metric-card paper"><strong>02</strong><h3>Every route</h3><p>Sequential, parallel, quorum, conditional, and automatic.</p></div><div className="metric-card mint"><strong>03</strong><h3>100%</h3><p>Append-only audit history built for proof and accountability.</p></div></div></div></section>
      <section className="features section-shell" id="features"><div className="section-heading split"><div><Eyebrow>Core capabilities</Eyebrow><h2>Designed for speed.<br/>Engineered for proof.</h2></div><p>Everything your team needs to request, route, decide, and report—without adding process theatre.</p></div><div className="feature-tabs" role="tablist" aria-label="ApprovalDesk capabilities">{featureGroups.map((group, index)=><button key={group[0]} id={`feature-tab-${group[0]}`} type="button" role="tab" aria-selected={featureTab===index} aria-controls={`feature-panel-${group[0]}`} tabIndex={featureTab===index?0:-1} onClick={()=>setFeatureTab(index)}>{String(index + 1).padStart(2,"0")} <span>{group[1]}</span></button>)}</div><div className="feature-layout feature-tab-layout" onMouseEnter={()=>setFeaturePaused(true)} onMouseLeave={()=>setFeaturePaused(false)} onFocusCapture={()=>setFeaturePaused(true)} onBlurCapture={event=>{if(!event.currentTarget.contains(event.relatedTarget)) setFeaturePaused(false)}}>{featureGroups.map((group, index)=><div className={`feature-progress ${featureTab===index?"active":""}`} key={group[0]} aria-hidden="true" />)}<div className="feature-groups" id={`feature-panel-${featureGroups[featureTab][0]}`} role="tabpanel" aria-labelledby={`feature-tab-${featureGroups[featureTab][0]}`}><article className="feature-group"><div className="feature-group-top"><p className="micro">{featureGroups[featureTab][1].toUpperCase()}</p><span>{featurePaused ? "PAUSED ON HOVER" : "AUTO-CYCLING"}</span></div><h3>{featureGroups[featureTab][2]}</h3>{featureGroups[featureTab][3].map((item, index)=><div className="feature-row" key={item[0]}><span className="feature-row-index">0{index + 1}</span><b>{item[0]}</b><p>{item[1]}</p></div>)}</article></div></div></section>
      <section className="industries" id="industries"><div className="section-shell"><div className="section-heading split"><div><Eyebrow>Built for real work</Eyebrow><h2>Every industry has approvals. Now they have a system.</h2></div><a className="text-link" href="#demo" onClick={event=>{event.preventDefault();openLead("demo")}}>See ApprovalDesk for your team ↗</a></div><div className="case-feature"><img src="/images/sections/healthcare-team.png" alt="Healthcare administrators acting on an equipment request"/><div className="case-overlay"><p className="micro">HEALTHCARE / URGENT SUPPLY REQUEST</p><h3>Make urgent work visible before it becomes overdue.</h3><p>SLA timers, escalation, and a complete decision timeline keep critical requests moving.</p></div><span className="case-badge">AUDIT READY</span></div><div className="industry-list">{industries.map((x,i)=><article key={x[0]}><span>{String(i+1).padStart(2,"0")}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></div></section>
      <section className="security section-shell" id="security"><div className="security-copy"><Eyebrow>Security & control</Eyebrow><h2>Protected infrastructure, without the operational burden.</h2><p>ApprovalDesk is delivered as a managed instance, with infrastructure, deployment, and ongoing maintenance handled by our team. You stay focused on the work while we keep the service running.</p><ActionLink onClick={()=>openLead("demo")}>Talk to our team</ActionLink></div><div className="security-panel"><div className="radar" aria-label="Protected records"><span className="pulse p1"/><span className="pulse p2"/><span className="pulse p3"/><span className="security-sweep" aria-hidden="true"/><div className="radar-center"><ShieldCheckIcon size={74} weight="regular" aria-hidden="true"/></div></div><div className="security-list">{["Role-based access","Passkeys, 2FA & SSO","Signed, expiring links","Team-managed instance"].map((x,i)=><p key={x}><span>0{i+1}</span><b>{x}</b></p>)}</div></div></section>
      <section className="comparison"><div className="section-shell"><div className="section-heading centered"><Eyebrow>Why teams switch</Eyebrow><h2>Less chasing.<br/>More accountable action.</h2></div><div className="compare-grid"><div className="compare-card old"><p className="micro">THE OLD WAY</p><h3>“I sent you a message about it.”</h3><ul><li>Files move desk to desk</li><li>Approvals disappear during leave</li><li>Slowdowns stay invisible</li><li>Audit evidence is reconstructed</li></ul></div><div className="compare-card new"><p className="micro">WITH APPROVALDESK</p><h3>Every request has one source of truth.</h3><ul><li>Requests route automatically</li><li>Delegation keeps work moving</li><li>Bottlenecks surface in real time</li><li>The full timeline is always ready</li></ul></div></div></div></section>
      <section className="faq section-shell" id="faq"><div className="faq-title"><Eyebrow>Frequently asked questions</Eyebrow><h2>Good questions.<br/>Clear answers.</h2><p>Still deciding whether ApprovalDesk fits your organisation?</p><a href="#demo" onClick={event=>{event.preventDefault();openLead("demo")}}>Talk to a product specialist ↗</a></div><div className="faq-list">{faqs.map((x,i)=><article className={openFaq===i?"open":""} key={x[0]}><button onClick={()=>setOpenFaq(openFaq===i?-1:i)}><span>{x[0]}</span><em>{openFaq===i?"Hide":"Answer"}</em></button><div><p>{x[1]}</p></div></article>)}</div></section>
      <section className="final-cta" id="demo"><div className="section-shell final-grid"><div><Eyebrow>Ready when you are</Eyebrow><h2>Ready to end approval chaos?</h2><p>See every request, speed up every decision, and prove every action.</p></div><div className="demo-invite"><p className="micro">TAILORED WALKTHROUGH</p><h3>See ApprovalDesk with your workflow in mind.</h3><p>Share a few details and we’ll prepare the right conversation for your team.</p><button type="button" onClick={()=>openLead("demo")}>Book a demo <span>↗</span></button><small>Prefer SaaS? <a href="#demo" onClick={event=>{event.preventDefault();openLead("waitlist")}}>Join the waitlist.</a></small></div></div></section>
    </main>
    <footer><div className="section-shell footer-grid"><div><Brand tone="white"/><p>Audit-ready approval workflow software.</p></div><div><b>Explore</b><a href="#how">How it works</a><a href="#features">Features</a><a href="#industries">Industries</a></div><div><b>Company</b><a href="#demo" onClick={event=>{event.preventDefault();openLead("demo")}}>Book a demo</a><a href="#security">Security</a><a href="#faq">FAQ</a></div><div><b>Contact</b><a href="mailto:hello@ohrsystems.ng">hello@ohrsystems.ng</a><a href="mailto:hello@ichanneltech.com">hello@ichanneltech.com</a><p>Developed by OHR Systems<br/>Supported by IChannel Technologies</p></div></div><div className="section-shell footer-bottom"><span>© 2026 ApprovalDesk</span><span className="footer-legal"><a href="/privacy">Privacy</a><i>·</i><a href="/terms">Terms</a></span><a href="#top">Back to top ↑</a></div></footer>
    {leadMode && <LeadModal mode={leadMode} onClose={()=>setLeadMode(null)} />}
  </div>;
}
