import { useEffect } from "react";
import { setPageMetadata } from "./seo.js";

const policies = {
  privacy: {
    eyebrow: "Trust & data governance",
    title: "Privacy Policy",
    summary: "How ApprovalDesk handles personal information when we provide and support your organisation’s managed approval-workflow instance.",
    sections: [
      ["1. Scope, responsible companies, and our role", <><p>This policy applies to the ApprovalDesk website, managed product instances, support services, and related business communications. ApprovalDesk is developed by <strong>OHR Systems</strong> and supported by <strong>IChannel Technologies</strong>. Both companies are registered in Nigeria.</p><p>Your organisation decides why and how request, workflow, and employee information is used in its ApprovalDesk instance. In that context, the organisation is generally the data controller and the ApprovalDesk provider identified in its service agreement acts as a data processor or service provider. OHR Systems and IChannel Technologies may each act as a controller for account, security, support, commercial, and website information they collect for their own business purposes.</p></>],
      ["2. Information we process", <><p>Depending on how your organisation configures ApprovalDesk, we may process:</p><ul><li>Account and organisation details, including names, work email addresses, roles, departments, managers, and optional telephone numbers.</li><li>Request content, custom form answers, attachments, comments, mentions, approval decisions, conditions, delegations, deadlines, and workflow history.</li><li>Security and technical records, such as sign-in events, device and session information, IP-derived location signals, audit events, and delivery logs.</li><li>Support and commercial information, including messages, configuration details, service contacts, and order or billing records.</li><li>Integration data needed to deliver notifications or approved post-workflow actions through services your organisation enables.</li></ul></>],
      ["3. Sources, purposes, and lawful bases", <><p>Information may come from you, your organisation and its administrators, other Authorised Users, customer-enabled integrations, and the devices and systems used to access the service.</p><p>We process information to provide, secure, maintain, and support ApprovalDesk; route requests to authorised people; record decisions; deliver notifications; generate reports and evidence packs; troubleshoot incidents; prevent abuse; and meet contractual or legal obligations. Where applicable, we rely on performance of a contract, legitimate interests in operating and securing the service, compliance with legal obligations, or consent for a specific optional activity.</p><p>We do not sell personal information. We do not use the contents of your organisation’s requests or attachments for third-party advertising.</p></>],
      ["4. Customer control and lawful use", <><p>Your organisation controls its forms, workflows, users, permissions, integrations, and retention requirements. It is responsible for having a lawful basis to submit personal information to ApprovalDesk, giving appropriate notices to its users, and avoiding unnecessary collection of sensitive data.</p><p>Administrators can restrict sensitive fields, manage user access, review security events, and anonymise former users while preserving decision history where accountability records must remain intact.</p></>],
      ["5. Sharing and subprocessors", <><p>We disclose information only as needed to operate the service, follow your organisation’s instructions, comply with law, protect the service and its users, or complete a business transaction subject to appropriate safeguards.</p><p>Service providers may support managed hosting, email delivery, monitoring, backups, customer support, or other operational functions. Customer-enabled integrations receive only the information needed for the action your organisation configures. Those services apply their own terms and privacy practices.</p></>],
      ["6. Security", <><p>ApprovalDesk uses administrative, technical, and organisational safeguards appropriate to the service, including role-based access, encrypted connections, protected credentials, time-limited signed links, access logging, backups, and optional multi-factor controls.</p><p>No service can guarantee absolute security. Customers should configure least-privilege access, protect administrator accounts, review integrations, and promptly report suspected compromise.</p></>],
      ["7. Retention, audit records, and deletion", <><p>We retain information for as long as needed to provide the managed service, satisfy the customer’s documented requirements, resolve disputes, maintain security, and meet legal obligations. Retention periods may vary by customer configuration and service agreement.</p><p>ApprovalDesk is designed to preserve an append-only history of workflow actions. When a person has participated in a recorded business decision, account deletion may be replaced with anonymisation so the organisation can retain an accountable audit trail. Customers can request exports and agree offboarding or deletion arrangements with our team.</p></>],
      ["8. International processing", <p>Managed infrastructure and service providers may process information outside the country where a user works. Where required, we use contractual and organisational safeguards for international transfers and discuss data-location requirements during customer onboarding.</p>],
      ["9. Your choices and rights", <><p>Depending on applicable law, individuals may have rights to be informed; access, correct, or export their information; restrict or object to processing; withdraw consent; request deletion; and raise a complaint with the data-protection authority responsible for their location.</p><p>For information held in an organisation’s ApprovalDesk instance, contact that organisation first. We will support verified customer requests as required by our agreement and applicable law. For information controlled directly by ApprovalDesk, contact us using the details below. We may need to verify identity before completing a request.</p></>],
      ["10. Website data and cookies", <p>Our website may use essential storage or cookies needed for security, preferences, and basic operation. If we introduce non-essential analytics or marketing technologies, we will provide any notice and choices required by applicable law.</p>],
      ["11. Children", <p>ApprovalDesk is a business service and is not directed to children. Organisations must not use it to collect children’s personal information unless they have an appropriate lawful basis, safeguards, and a use case agreed with us.</p>],
      ["12. Changes and contact", <><p>We may update this policy as the product, operating model, or law changes. We will publish the revised date and provide additional notice when a material change requires it.</p><p>For product and privacy enquiries, contact OHR Systems at <strong>hello@ohrsystems.ng</strong>. For implementation and support enquiries, contact IChannel Technologies at <strong>hello@ichanneltech.com</strong>.</p></>],
    ],
  },
  terms: {
    eyebrow: "Service terms",
    title: "Terms of Service",
    summary: "The terms that govern access to ApprovalDesk’s managed approval-workflow service.",
    sections: [
      ["1. Agreement, responsible companies, and business use", <><p>These Terms of Service govern access to ApprovalDesk’s website, managed product instances, support, and related services. ApprovalDesk is developed by <strong>OHR Systems</strong> and supported by <strong>IChannel Technologies</strong>, both companies registered in Nigeria. “ApprovalDesk”, “we”, “us”, and “our” refer to the relevant provider or providers identified in the Customer’s order form or service agreement. “Customer” means the organisation that obtains the service, and “Authorised Users” are the people it permits to use ApprovalDesk.</p><p>By ordering, accessing, or using the service, you confirm that you have authority to bind the Customer to these terms. ApprovalDesk is intended for organisational and professional use, not personal or household use.</p></>],
      ["2. The managed service", <><p>ApprovalDesk provides configurable request forms, approval workflows, decision records, collaboration features, reporting, notifications, and related controls through an instance managed by our team. OHR Systems develops the product, while IChannel Technologies provides implementation and support services. The relevant provider supplies the infrastructure, deployment, maintenance, and operational support described in the applicable order.</p><p>ApprovalDesk is not offered for customer self-hosting. A separate multi-tenant SaaS version is planned but is not currently part of the service unless we expressly agree otherwise in writing.</p></>],
      ["3. Customer accounts and administration", <><p>The Customer controls its Authorised Users, roles, departments, workflows, request types, integrations, and internal policies. It must keep account information accurate, assign access on a least-privilege basis, protect credentials, and promptly remove access when a person no longer needs it.</p><p>The Customer is responsible for actions taken through its accounts except to the extent caused by our breach. Administrators and the system owner hold elevated privileges and must be appointed carefully.</p></>],
      ["4. Acceptable use", <><p>You must not use ApprovalDesk to break the law; infringe another person’s rights; distribute malware; attempt unauthorised access; disrupt or probe the service; evade security or usage limits; send unlawful communications; or process data you are not entitled to use.</p><p>You must not reverse engineer the service except where applicable law expressly permits it, resell access without written permission, or use automated means in a way that materially degrades the service. We may investigate suspected misuse and take proportionate steps to protect customers and the platform.</p></>],
      ["5. Customer data and instructions", <><p>The Customer retains its rights in information submitted to its instance. The Customer grants us a limited right to host, copy, transmit, back up, and otherwise process that information only to provide, secure, maintain, and support the service or comply with law.</p><p>The Customer is responsible for the legality, accuracy, and quality of its data and instructions. It should not collect sensitive information unless needed for a legitimate business purpose and protected with suitable access controls.</p></>],
      ["6. Audit integrity and records", <><p>ApprovalDesk is designed to preserve append-only workflow and decision history. The Customer acknowledges that recorded approvals, rejections, delegations, revisions, and related evidence may remain part of its business record even when an account is deactivated or anonymised.</p><p>ApprovalDesk supports operational accountability but does not determine whether a workflow, approval, evidence pack, or electronic action satisfies a particular regulatory, legal, accounting, or signature requirement. The Customer must obtain its own professional advice for those requirements.</p></>],
      ["7. Integrations and third-party services", <p>The Customer may enable external services for identity, notifications, file delivery, webhooks, or post-approval actions. The Customer authorises us to exchange the data needed to perform those instructions. We are not responsible for third-party services, their availability, or their handling of data, and their separate terms may apply.</p>],
      ["8. Fees, orders, and taxes", <p>Fees, billing dates, service period, user or capacity limits, and any implementation work are set out in the applicable order form or service agreement. Fees are exclusive of taxes unless stated otherwise. The Customer must pay undisputed amounts when due and notify us promptly of a billing dispute.</p>],
      ["9. Availability, maintenance, and support", <><p>We will operate and support the managed service with reasonable skill and care. We may perform planned maintenance, deploy security updates, or make changes needed for reliability and compliance. Where practical, we will give advance notice of material planned disruption.</p><p>Specific support hours, response targets, backup arrangements, data location, and service levels apply only when included in the Customer’s order or service agreement.</p></>],
      ["10. Confidentiality and security", <><p>Each party must protect the other party’s non-public business, technical, and security information using reasonable care and use it only to perform or receive the service. This obligation does not cover information that is public without breach, already lawfully known, independently developed, or lawfully received from another source.</p><p>If disclosure is legally required, the receiving party will provide notice when permitted and disclose only what is required. Our processing of personal information is also described in the ApprovalDesk Privacy Policy and any applicable data-processing agreement.</p></>],
      ["11. Intellectual property and feedback", <p>ApprovalDesk and its licensors retain all rights in the service, software, designs, documentation, and related technology. Except for the limited right to use the service during the agreed term, no rights are transferred. If you provide feedback, you permit us to use it without restriction or payment, provided we do not identify the Customer publicly without permission.</p>],
      ["12. Suspension and termination", <><p>We may suspend affected access when reasonably necessary to address a security risk, unlawful use, material breach, non-payment, or threat to the service or other customers. Where practical, we will give notice and work with the Customer to restore access.</p><p>Either party may terminate as stated in the applicable order or service agreement. On termination, access ends and the Customer should export needed records. We will handle remaining Customer data according to the agreed offboarding period, legal obligations, and our Privacy Policy.</p></>],
      ["13. Warranties and disclaimers", <><p>We warrant that we will provide the managed service with reasonable skill and care. If we materially breach that warranty, the Customer must notify us and allow a reasonable opportunity to correct the issue.</p><p>Except as expressly stated and to the extent permitted by law, the service is provided without implied warranties, including merchantability, fitness for a particular purpose, non-infringement, or uninterrupted operation. ApprovalDesk does not replace legal, compliance, financial, or professional judgment.</p></>],
      ["14. Liability", <><p>Neither party is liable for indirect, incidental, special, punitive, or consequential loss, or for lost profits, revenue, goodwill, or anticipated savings, except where applicable law does not allow that exclusion.</p><p>Any aggregate liability cap, exclusions from that cap, indemnities, and mandatory statutory rights will be set out in the applicable order form or service agreement. Nothing in these terms limits liability that cannot lawfully be limited.</p></>],
      ["15. Changes, governing terms, and contact", <><p>We may update these terms to reflect product, security, operational, or legal changes. Material changes will apply prospectively with appropriate notice. If an order form, data-processing agreement, or master services agreement conflicts with these website terms, the signed agreement controls for that Customer.</p><p>Governing law and dispute venue are stated in the applicable signed agreement. Product and commercial enquiries may be sent to OHR Systems at <strong>hello@ohrsystems.ng</strong>. Implementation and support enquiries may be sent to IChannel Technologies at <strong>hello@ichanneltech.com</strong>.</p></>],
    ],
  },
};

export function LegalPage({ type }) {
  const policy = policies[type];

  useEffect(() => {
    setPageMetadata({ title: `${policy.title} | ApprovalDesk`, description: policy.summary, path: type === "privacy" ? "/privacy" : "/terms" });
    window.scrollTo(0, 0);
  }, [policy.summary, policy.title, type]);

  return <main className="legal-page">
    <header className="legal-header">
      <img src="/images/brand/approvaldesk-logo-dark.png" alt="ApprovalDesk" />
      <a className="legal-back" href="/">← Back to home</a>
    </header>
    <article className="legal-document">
      <div className="legal-hero">
        <p className="legal-eyebrow">{policy.eyebrow}</p>
        <h1>{policy.title}</h1>
        <p className="legal-summary">{policy.summary}</p>
        <p className="legal-date">Last updated 27 August 2026</p>
      </div>
      <div className="legal-content">
        {policy.sections.map(([title, content]) => <section key={title}>
          <h2>{title}</h2>
          <div>{content}</div>
        </section>)}
      </div>
      <div className="legal-close">
        <p>ApprovalDesk</p>
        <span>Managed approval infrastructure for accountable teams.</span>
      </div>
    </article>
  </main>;
}
